Add script error check
Supports #3

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -40,16 +40,32 @@ function abort()
 
 function whitespace_error_check()
 {
-	message "Checking for whitespace errors... "
+	message "Checking for whitespace errors ... "
 
-	if ! git -C "$repository_dir" diff-index --check --cached $against -- >/dev/null 2>&1; then
-		echo "FAIL"
+	if ! git -C "$repository_dir" diff-index --check --cached "$against" -- >/dev/null 2>&1; then
+		echo "fail"
 		error "Aborting commit due to whitespace error(s). See below."
-		git -C "$repository_dir" diff-index --check --cached $against --
+		git -C "$repository_dir" diff-index --check --cached "$against" --
 		abort
 	fi
 
-		echo "PASS"
+		echo "pass"
+}
+
+function script_error_check()
+{
+	message "Checking for script errors ....... "
+
+	mapfile -t scripts < <( find "$repository_dir" -executable -type f | sed '/sample/d' )
+
+	if ! shellcheck -C always -s bash "${scripts[@]}" >/dev/null 2>&1; then
+		echo "fail"
+		error "Aborting commit due to script error(s). See below."
+		shellcheck -C always -s bash "${scripts[@]}"
+		abort
+	fi
+
+	echo "pass"
 }
 
 function main()
@@ -68,6 +84,7 @@ function main()
 	fi
 
 	whitespace_error_check
+	script_error_check
 }
 
 main "$@" 
